<?php

$bbcode = array(
	'code' => array(
		'/\[i\](.*?)\[\/i\]/is',
		'/\[b\](.*?)\[\/b\]/is',
		'/\[u\](.*?)\[\/u\]/is',
		'/\[s\](.*?)\[\/s\]/is',
		'/\[img\](.*?)\[\/img\]/is',
		'/\[img=(.*?)\]/is',
		'/\[url=(.*?)\](.*?)\[\/url\]/is',
		'/\[url\](.*?)\[\/url\]/is',
		'/\[size=1\](.*?)\[\/size\]/is',
		'/\[size=2\](.*?)\[\/size\]/is',
		'/\[size=3\](.*?)\[\/size\]/is',
		'/\[size=4\](.*?)\[\/size\]/is',
		'/\[size=5\](.*?)\[\/size\]/is',
		'/\[size=6\](.*?)\[\/size\]/is',
		'/\[size=7\](.*?)\[\/size\]/is',
		'/\[size=8\](.*?)\[\/size\]/is',
		'/\[color=(.*?)\](.*?)\[\/color\]/is',
		'/\[font=(.*?)\](.*?)\[\/font\]/is',
		'/\[align=(.*?)\](.*?)\[\/align\]/is',
		'/\[hr\]/is',
		'/\[center\](.*?)\[\/center\]/is',
		'/\[youtube\](.*?)\[\/youtube\]/is',
		'/\[swf=(.*?)\]/is',
		'/\[code\](.*?)\[\/code\]/is',
		'/\[quote\](.*?)\[\/quote\]/is',
		'/\[quote\](.*?)\[\/quote\]/is',
		'/\[quote\](.*?)\[\/quote\]/is',
		'/\[table\](.*?)\[\/table\]/is',
		'/\[tr\](.*?)\[\/tr\]/is',
		'/\[td\](.*?)\[\/td\]/is',
		'/\[list\](.*?)\[\/list\]/is',
		'/\[list=(.*?)\](.*?)\[\/list\]/is',
		'/\[\*\](.*)/',
		'/\[justify\](.*?)\[\/justify\]/is',
		'/\[right\](.*?)\[\/right\]/is',
		'/\[left\](.*?)\[\/left\]/is',
		'/\{(.*?)\}/is',
		'/\[(.*?)\]/is',
	),
	'html' => array(
		'<i>$1</i>',
		'<b>$1</b>',
		'<u>$1</u>',
		'<s>$1</s>',
		'<img src="$1" />',
		'<img src="$1" />',
		'<a href="$1" target="_blank">$2</a>',
		'<a href="$1" target="_blank">$1</a>',
		'<span style="font-size:10px">$1</span>',
		'<span style="font-size:12px">$1</span>',
		'<span style="font-size:15px">$1</span>',
		'<span style="font-size:17px">$1</span>',
		'<span style="font-size:23px">$1</span>',
		'<span style="font-size:31px">$1</span>',
		'<span style="font-size:47px">$1</span>',
		'<span style="font-size:54px">$1</span>',
		'<span style="color:$1">$2</span>',
		'<span style="font-family:$1">$2</span>',
		'<p style="text-align:$1;">$2</p>',
		'<hr />',
		'<center>$1</center>',
		'<object width="598" height="480"><param name="movie" value="http://www.youtube.com/v/$1"></param><param name="wmode" value="transparent"></param><embed src="http://www.youtube.com/v/$1" type="application/x-shockwave-flash" wmode="transparent" width="598" height="480" allowfullscreen="true"></embed></object>',
		'<embed width="598" height="390" wmode="transparent" autoplay="false" allownetworking="internal" allowfullscreen="true" type="application/x-shockwave-flash" quality="high" src="$1">',
		'<pre>$1</pre>',
		'<blockquote>$1</blockquote>',
		'<blockquote>$1</blockquote>',
		'<blockquote>$1</blockquote>',
		'<table border="1" cellpadding="10">$1</table>',
		'<tr>$1</tr>',
		'<td>$1</td>',
		'<ul>$1</ul>',
		'<ol type="$1">$2</ol>',
		'<li>$1</li>',
		'<p style="text-align:justify;">$1</p>',
		'<p style="text-align:right;">$1</p>',
		'<p style="text-align:left;">$1</p>',
		'&#123;$1&#125;',
		'&#91;$1&#93;',
	)
);