<?php
	$secciones = array(
		'inicio' => array(
			'id' => 'inicio',
			'titulo' => 'Página de Inicio',
			'url' => 'inicio',
			'clase' => 'seccion',
			'tipo' => 0,
			'filesec' => 'sec_inicio',
			'loging' => 0,
		),
		'error404' => array(
			'id' => 'error404',
			'titulo' => 'Error 404',
			'url' => 'error404',
			'clase' => 'seccion',
			'tipo' => 0,
			'filesec' => 'sec_error404',
			'loging' => 0,
		),
		'busqueda' => array(
			'id' => 'busqueda',
			'titulo' => 'Busqueda',
			'url' => 'busqueda',
			'clase' => 'seccion',
			'tipo' => 0,
			'filesec' => 'sec_busqueda',
			'loging' => 0,
		),
		'acceso' => array(
			'id' => 'acceso',
			'titulo' => 'Página de acceso',
			'url' => 'acceso',
			'clase' => 'seccion',
			'tipo' => 0,
			'filesec' => 'sec_acceso',
			'loging' => -1,
		),
		'registro' => array(
			'id' => 'registro',
			'titulo' => 'Página de registro',
			'url' => 'registro',
			'clase' => 'seccion',
			'tipo' => 0,
			'filesec' => 'sec_registro',
			'loging' => -1,
		),
		'salir' => array(
			'id' => 'salir',
			'titulo' => 'Cerrar sesión',
			'url' => 'salir',
			'clase' => 'seccion',
			'tipo' => 0,
			'filesec' => 'sec_salir',
			'loging' => -1,
		),
		'post' => array(
			'id' => 'post',
			'titulo' => 'Editor de post',
			'url' => 'post',
			'clase' => 'seccion',
			'tipo' => 0,
			'filesec' => 'sec_post',
			'loging' => 1,
		),
		'rss' => array(
			'id' => 'rss',
			'titulo' => 'RSS',
			'url' => 'rss',
			'clase' => 'seccion',
			'tipo' => 0,
			'filesec' => 'sec_rss',
			'loging' => 0,
		),
		'sitemap.xml' => array(
			'id' => 'sitemap',
			'titulo' => 'Sitemap',
			'url' => 'sitemap.xml',
			'clase' => 'seccion',
			'tipo' => 0,
			'filesec' => 'sec_sitemap',
			'loging' => 0,
		),
		'perfil' => array(
			'id' => 'perfil',
			'titulo' => 'perfil',
			'url' => 'perfil',
			'clase' => 'seccion',
			'tipo' => 0,
			'filesec' => 'sec_perfil',
			'loging' => 0,
		),
		'cuenta' => array(
			'id' => 'cuenta',
			'titulo' => 'cuenta',
			'url' => 'cuenta',
			'clase' => 'seccion',
			'tipo' => 0,
			'filesec' => 'sec_cuenta',
			'loging' => 1,
		),
		'tienda' => array(
			'id' => 'tienda',
			'titulo' => 'Tienda',
			'url' => 'tienda',
			'clase' => 'seccion',
			'tipo' => 0,
			'filesec' => 'sec_tienda',
			'loging' => 1,
		),
		'contacto' => array(
			'id' => 'contacto',
			'titulo' => 'Página de contacto',
			'url' => 'contacto',
			'clase' => 'seccion',
			'tipo' => 0,
			'filesec' => 'sec_contacto',
			'loging' => 0,
		),
		'public_coment' => array(
			'id' => 'public_coment',
			'titulo' => '',
			'url' => 'public_coment',
			'clase' => 'seccion',
			'tipo' => 0,
			'filesec' => 'sec_public_coment',
			'loging' => 0,
		),
		'autosc' => array(
			'id' => 'autosc',
			'titulo' => '',
			'url' => 'autosc',
			'clase' => 'seccion',
			'tipo' => 0,
			'filesec' => 'sec_autosc',
			'loging' => 0,
		),
		'pedidos' => array(
			'id' => 'pedidos',
			'titulo' => 'Solicitar un anime',
			'url' => 'pedidos',
			'clase' => 'seccion',
			'tipo' => 0,
			'filesec' => 'sec_pedidos',
			'loging' => 1,
		),
		'referidos' => array(
			'id' => 'referidos',
			'titulo' => 'Referidos',
			'url' => 'referidos',
			'clase' => 'seccion',
			'tipo' => 0,
			'filesec' => 'sec_referidos',
			'loging' => 1,
		),
		'tops' => array(
			'id' => 'tops',
			'titulo' => 'tops',
			'url' => 'tops',
			'clase' => 'seccion',
			'tipo' => 0,
			'filesec' => 'sec_tops',
			'loging' => 0,
		),
	);
